services:
  db:
    image: mysql:8.0
    container_name: cifra_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cifra_solicitudes
      MYSQL_USER: cifra
      MYSQL_PASSWORD: cifra
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
volumes:
  db_data:
